<a href="https://colab.research.google.com/github/Puspita02/AI-generated-Text-Detector/blob/main/01_Main_Pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
%cd /content

!git clone https://github.com/Puspita02/Prompt-Bias-Mitigation-SLM-Judge.git

/content
Cloning into 'Prompt-Bias-Mitigation-SLM-Judge'...
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (3/3), done.

In [3]:
%cd Prompt-Bias-Mitigation-SLM-Judge

/content/Prompt-Bias-Mitigation-SLM-Judge

In [4]:
import os

folders = [
    "datasets",
    "results",
    "figures",
    "logs",
    "prompts"
]

for folder in folders:
    os.makedirs(folder, exist_ok=True)

print("Project folders created successfully.")

Project folders created successfully.

In [5]:
!pip -q install transformers
!pip -q install datasets
!pip -q install accelerate

In [6]:
import torch
import transformers
import datasets
import huggingface_hub
import pandas
import numpy

print("Torch:", torch.__version__)
print("Transformers:", transformers.__version__)
print("Datasets:", datasets.__version__)
print("HF Hub:", huggingface_hub.__version__)
print("Pandas:", pandas.__version__)
print("NumPy:", numpy.__version__)

Torch: 2.11.0+cu128
Transformers: 5.12.1
Datasets: 4.0.0
HF Hub: 1.20.1
Pandas: 2.2.2
NumPy: 2.0.2

In [7]:
from pathlib import Path

PROJECT_ROOT = Path("/content/Prompt-Bias-Mitigation-SLM-Judge")

DATA_DIR = PROJECT_ROOT / "datasets"
RESULT_DIR = PROJECT_ROOT / "results"
FIGURE_DIR = PROJECT_ROOT / "figures"
LOG_DIR = PROJECT_ROOT / "logs"

DATA_DIR.mkdir(exist_ok=True)
RESULT_DIR.mkdir(exist_ok=True)
FIGURE_DIR.mkdir(exist_ok=True)
LOG_DIR.mkdir(exist_ok=True)

print(PROJECT_ROOT)

/content/Prompt-Bias-Mitigation-SLM-Judge

In [8]:
from pathlib import Path

PROJECT_ROOT = Path("/content/Prompt-Bias-Mitigation-SLM-Judge")

RAW_DATA = PROJECT_ROOT / "datasets" / "raw"
PROCESSED_DATA = PROJECT_ROOT / "datasets" / "processed"

for folder in [
    RAW_DATA / "mtbench",
    RAW_DATA / "llmbar",
    PROCESSED_DATA,
]:
    folder.mkdir(parents=True, exist_ok=True)

print("Dataset folders created successfully.")

Dataset folders created successfully.

In [9]:
from datasets import load_dataset

mtbench = load_dataset("lmsys/mt_bench_human_judgments")

mt_df = mtbench["gpt4_pair"].to_pandas()

mt_df.to_csv(
    RAW_DATA / "mtbench" / "mtbench.csv",
    index=False
)

print(mt_df.shape)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md:   0%|          | 0.00/2.00k [00:00<?, ?B/s]

data/gpt4_pair-00000-of-00001-c0b431264a(…):   0%|          | 0.00/650k [00:00<?, ?B/s]

data/human-00000-of-00001-25f49108187592(…):   0%|          | 0.00/739k [00:00<?, ?B/s]

Generating gpt4_pair split:   0%|          | 0/2400 [00:00<?, ? examples/s]

Generating human split:   0%|          | 0/3355 [00:00<?, ? examples/s]

(2400, 8)

In [10]:
import os

%cd /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw

if not os.path.exists("LLMBar"):
    !git clone https://github.com/princeton-nlp/LLMBar.git

print("LLMBar repository ready.")

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw
Cloning into 'LLMBar'...
remote: Enumerating objects: 1725, done.
remote: Counting objects: 100% (1725/1725), done.
remote: Compressing objects: 100% (1227/1227), done.
remote: Total 1725 (delta 507), reused 1708 (delta 497), pack-reused 0 (from 0)
Receiving objects: 100% (1725/1725), 10.62 MiB | 12.24 MiB/s, done.
Resolving deltas: 100% (507/507), done.
LLMBar repository ready.

In [11]:
!ls -R /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar:
Dataset  LICENSE  LLMEvaluator	README.md  requirements.txt

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset:
CaseStudy  LLMBar  Processed

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy:
Base_10  Base_9  Constraint  Negation  Normal

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_10:
dataset.json  evaluators

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_10/evaluators:
ChatGPT  ChatGPT-0301  Falcon  GPT-4  LLaMA2  PaLM2

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_10/evaluators/ChatGPT:
CoT  Metrics_Reference	Swap  Swap_CoT	Vanilla

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_10/evaluators/ChatGPT/CoT:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_10/evaluators/ChatGPT/Metrics_Reference:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_10/evaluators/ChatGPT/Swap:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_10/evaluators/ChatGPT/Swap_CoT:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_10/evaluators/ChatGPT/Vanilla:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_10/evaluators/ChatGPT-0301:
CoT  Metrics_Reference	Swap  Swap_CoT	Vanilla

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_10/evaluators/ChatGPT-0301/CoT:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_10/evaluators/ChatGPT-0301/Metrics_Reference:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_10/evaluators/ChatGPT-0301/Swap:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_10/evaluators/ChatGPT-0301/Swap_CoT:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_10/evaluators/ChatGPT-0301/Vanilla:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_10/evaluators/Falcon:
CoT  Metrics_Reference	Swap  Swap_CoT	Vanilla

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_10/evaluators/Falcon/CoT:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_10/evaluators/Falcon/Metrics_Reference:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_10/evaluators/Falcon/Swap:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_10/evaluators/Falcon/Swap_CoT:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_10/evaluators/Falcon/Vanilla:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_10/evaluators/GPT-4:
CoT  Metrics_Reference	Swap  Swap_CoT	Vanilla

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_10/evaluators/GPT-4/CoT:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_10/evaluators/GPT-4/Metrics_Reference:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_10/evaluators/GPT-4/Swap:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_10/evaluators/GPT-4/Swap_CoT:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_10/evaluators/GPT-4/Vanilla:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_10/evaluators/LLaMA2:
CoT  Metrics_Reference	Swap  Swap_CoT	Vanilla

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_10/evaluators/LLaMA2/CoT:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_10/evaluators/LLaMA2/Metrics_Reference:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_10/evaluators/LLaMA2/Swap:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_10/evaluators/LLaMA2/Swap_CoT:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_10/evaluators/LLaMA2/Vanilla:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_10/evaluators/PaLM2:
CoT  Metrics_Reference	Swap  Swap_CoT	Vanilla

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_10/evaluators/PaLM2/CoT:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_10/evaluators/PaLM2/Metrics_Reference:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_10/evaluators/PaLM2/Swap:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_10/evaluators/PaLM2/Swap_CoT:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_10/evaluators/PaLM2/Vanilla:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_9:
dataset.json  evaluators

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_9/evaluators:
ChatGPT  ChatGPT-0301  Falcon  GPT-4  LLaMA2  PaLM2

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_9/evaluators/ChatGPT:
CoT  Metrics_Reference	Swap  Swap_CoT	Vanilla

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_9/evaluators/ChatGPT/CoT:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_9/evaluators/ChatGPT/Metrics_Reference:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_9/evaluators/ChatGPT/Swap:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_9/evaluators/ChatGPT/Swap_CoT:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_9/evaluators/ChatGPT/Vanilla:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_9/evaluators/ChatGPT-0301:
CoT  Metrics_Reference	Swap  Swap_CoT	Vanilla

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_9/evaluators/ChatGPT-0301/CoT:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_9/evaluators/ChatGPT-0301/Metrics_Reference:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_9/evaluators/ChatGPT-0301/Swap:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_9/evaluators/ChatGPT-0301/Swap_CoT:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_9/evaluators/ChatGPT-0301/Vanilla:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_9/evaluators/Falcon:
CoT  Metrics_Reference	Swap  Swap_CoT	Vanilla

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_9/evaluators/Falcon/CoT:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_9/evaluators/Falcon/Metrics_Reference:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_9/evaluators/Falcon/Swap:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_9/evaluators/Falcon/Swap_CoT:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_9/evaluators/Falcon/Vanilla:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_9/evaluators/GPT-4:
CoT  Metrics_Reference	Swap  Swap_CoT	Vanilla

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_9/evaluators/GPT-4/CoT:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_9/evaluators/GPT-4/Metrics_Reference:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_9/evaluators/GPT-4/Swap:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_9/evaluators/GPT-4/Swap_CoT:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_9/evaluators/GPT-4/Vanilla:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_9/evaluators/LLaMA2:
CoT  Metrics_Reference	Swap  Swap_CoT	Vanilla

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_9/evaluators/LLaMA2/CoT:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_9/evaluators/LLaMA2/Metrics_Reference:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_9/evaluators/LLaMA2/Swap:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_9/evaluators/LLaMA2/Swap_CoT:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_9/evaluators/LLaMA2/Vanilla:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_9/evaluators/PaLM2:
CoT  Metrics_Reference	Swap  Swap_CoT	Vanilla

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_9/evaluators/PaLM2/CoT:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_9/evaluators/PaLM2/Metrics_Reference:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_9/evaluators/PaLM2/Swap:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_9/evaluators/PaLM2/Swap_CoT:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_9/evaluators/PaLM2/Vanilla:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Constraint:
dataset.json  evaluators

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Constraint/evaluators:
ChatGPT  ChatGPT-0301  Falcon  GPT-4  LLaMA2  PaLM2

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Constraint/evaluators/ChatGPT:
CoT  Metrics_Reference	Swap  Swap_CoT	Vanilla

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Constraint/evaluators/ChatGPT/CoT:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Constraint/evaluators/ChatGPT/Metrics_Reference:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Constraint/evaluators/ChatGPT/Swap:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Constraint/evaluators/ChatGPT/Swap_CoT:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Constraint/evaluators/ChatGPT/Vanilla:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Constraint/evaluators/ChatGPT-0301:
CoT  Metrics_Reference	Swap  Swap_CoT	Vanilla

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Constraint/evaluators/ChatGPT-0301/CoT:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Constraint/evaluators/ChatGPT-0301/Metrics_Reference:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Constraint/evaluators/ChatGPT-0301/Swap:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Constraint/evaluators/ChatGPT-0301/Swap_CoT:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Constraint/evaluators/ChatGPT-0301/Vanilla:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Constraint/evaluators/Falcon:
CoT  Metrics_Reference	Swap  Swap_CoT	Vanilla

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Constraint/evaluators/Falcon/CoT:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Constraint/evaluators/Falcon/Metrics_Reference:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Constraint/evaluators/Falcon/Swap:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Constraint/evaluators/Falcon/Swap_CoT:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Constraint/evaluators/Falcon/Vanilla:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Constraint/evaluators/GPT-4:
CoT  Metrics_Reference	Swap  Swap_CoT	Vanilla

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Constraint/evaluators/GPT-4/CoT:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Constraint/evaluators/GPT-4/Metrics_Reference:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Constraint/evaluators/GPT-4/Swap:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Constraint/evaluators/GPT-4/Swap_CoT:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Constraint/evaluators/GPT-4/Vanilla:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Constraint/evaluators/LLaMA2:
CoT  Metrics_Reference	Swap  Swap_CoT	Vanilla

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Constraint/evaluators/LLaMA2/CoT:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Constraint/evaluators/LLaMA2/Metrics_Reference:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Constraint/evaluators/LLaMA2/Swap:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Constraint/evaluators/LLaMA2/Swap_CoT:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Constraint/evaluators/LLaMA2/Vanilla:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Constraint/evaluators/PaLM2:
CoT  Metrics_Reference	Swap  Swap_CoT	Vanilla

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Constraint/evaluators/PaLM2/CoT:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Constraint/evaluators/PaLM2/Metrics_Reference:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Constraint/evaluators/PaLM2/Swap:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Constraint/evaluators/PaLM2/Swap_CoT:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Constraint/evaluators/PaLM2/Vanilla:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Negation:
dataset.json  evaluators

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Negation/evaluators:
ChatGPT  ChatGPT-0301  Falcon  GPT-4  LLaMA2  PaLM2

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Negation/evaluators/ChatGPT:
CoT  Metrics_Reference	Swap  Swap_CoT	Vanilla

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Negation/evaluators/ChatGPT/CoT:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Negation/evaluators/ChatGPT/Metrics_Reference:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Negation/evaluators/ChatGPT/Swap:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Negation/evaluators/ChatGPT/Swap_CoT:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Negation/evaluators/ChatGPT/Vanilla:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Negation/evaluators/ChatGPT-0301:
CoT  Metrics_Reference	Swap  Swap_CoT	Vanilla

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Negation/evaluators/ChatGPT-0301/CoT:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Negation/evaluators/ChatGPT-0301/Metrics_Reference:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Negation/evaluators/ChatGPT-0301/Swap:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Negation/evaluators/ChatGPT-0301/Swap_CoT:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Negation/evaluators/ChatGPT-0301/Vanilla:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Negation/evaluators/Falcon:
CoT  Metrics_Reference	Swap  Swap_CoT	Vanilla

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Negation/evaluators/Falcon/CoT:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Negation/evaluators/Falcon/Metrics_Reference:
result.json  statistics.json

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Negation/evaluators/Falcon/Swap:
result.json  statistics.json


In [12]:
!ls /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar

Dataset  LICENSE  LLMEvaluator	README.md  requirements.txt

In [13]:
!find /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset -type f

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_10/evaluators/LLaMA2/Metrics_Reference/statistics.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_10/evaluators/LLaMA2/Metrics_Reference/result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_10/evaluators/LLaMA2/Swap/statistics.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_10/evaluators/LLaMA2/Swap/result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_10/evaluators/LLaMA2/Swap_CoT/statistics.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_10/evaluators/LLaMA2/Swap_CoT/result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_10/evaluators/LLaMA2/CoT/statistics.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_10/evaluators/LLaMA2/CoT/result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_10/evaluators/LLaMA2/Vanilla/statistics.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_10/evaluators/LLaMA2/Vanilla/result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_10/evaluators/ChatGPT/Metrics_Reference/statistics.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_10/evaluators/ChatGPT/Metrics_Reference/result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_10/evaluators/ChatGPT/Swap/statistics.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_10/evaluators/ChatGPT/Swap/result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_10/evaluators/ChatGPT/Swap_CoT/statistics.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_10/evaluators/ChatGPT/Swap_CoT/result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_10/evaluators/ChatGPT/CoT/statistics.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_10/evaluators/ChatGPT/CoT/result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_10/evaluators/ChatGPT/Vanilla/statistics.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_10/evaluators/ChatGPT/Vanilla/result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_10/evaluators/ChatGPT-0301/Metrics_Reference/statistics.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_10/evaluators/ChatGPT-0301/Metrics_Reference/result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_10/evaluators/ChatGPT-0301/Swap/statistics.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_10/evaluators/ChatGPT-0301/Swap/result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_10/evaluators/ChatGPT-0301/Swap_CoT/statistics.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_10/evaluators/ChatGPT-0301/Swap_CoT/result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_10/evaluators/ChatGPT-0301/CoT/statistics.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_10/evaluators/ChatGPT-0301/CoT/result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_10/evaluators/ChatGPT-0301/Vanilla/statistics.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_10/evaluators/ChatGPT-0301/Vanilla/result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_10/evaluators/GPT-4/Metrics_Reference/statistics.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_10/evaluators/GPT-4/Metrics_Reference/result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_10/evaluators/GPT-4/Swap/statistics.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_10/evaluators/GPT-4/Swap/result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_10/evaluators/GPT-4/Swap_CoT/statistics.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_10/evaluators/GPT-4/Swap_CoT/result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_10/evaluators/GPT-4/CoT/statistics.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_10/evaluators/GPT-4/CoT/result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_10/evaluators/GPT-4/Vanilla/statistics.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_10/evaluators/GPT-4/Vanilla/result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_10/evaluators/Falcon/Metrics_Reference/statistics.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_10/evaluators/Falcon/Metrics_Reference/result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_10/evaluators/Falcon/Swap/statistics.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_10/evaluators/Falcon/Swap/result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_10/evaluators/Falcon/Swap_CoT/statistics.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_10/evaluators/Falcon/Swap_CoT/result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_10/evaluators/Falcon/CoT/statistics.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_10/evaluators/Falcon/CoT/result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_10/evaluators/Falcon/Vanilla/statistics.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_10/evaluators/Falcon/Vanilla/result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_10/evaluators/PaLM2/Metrics_Reference/statistics.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_10/evaluators/PaLM2/Metrics_Reference/result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_10/evaluators/PaLM2/Swap/statistics.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_10/evaluators/PaLM2/Swap/result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_10/evaluators/PaLM2/Swap_CoT/statistics.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_10/evaluators/PaLM2/Swap_CoT/result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_10/evaluators/PaLM2/CoT/statistics.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_10/evaluators/PaLM2/CoT/result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_10/evaluators/PaLM2/Vanilla/statistics.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_10/evaluators/PaLM2/Vanilla/result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Base_10/dataset.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Normal/evaluators/LLaMA2/Metrics_Reference/statistics.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Normal/evaluators/LLaMA2/Metrics_Reference/result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Normal/evaluators/LLaMA2/Swap/statistics.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Normal/evaluators/LLaMA2/Swap/result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Normal/evaluators/LLaMA2/Swap_CoT/statistics.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Normal/evaluators/LLaMA2/Swap_CoT/result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Normal/evaluators/LLaMA2/CoT/statistics.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Normal/evaluators/LLaMA2/CoT/result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Normal/evaluators/LLaMA2/Vanilla/statistics.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Normal/evaluators/LLaMA2/Vanilla/result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Normal/evaluators/ChatGPT/Metrics_Reference/statistics.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Normal/evaluators/ChatGPT/Metrics_Reference/result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Normal/evaluators/ChatGPT/Swap/statistics.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Normal/evaluators/ChatGPT/Swap/result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Normal/evaluators/ChatGPT/Swap_CoT/statistics.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Normal/evaluators/ChatGPT/Swap_CoT/result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Normal/evaluators/ChatGPT/CoT/statistics.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Normal/evaluators/ChatGPT/CoT/result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Normal/evaluators/ChatGPT/Vanilla/statistics.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Normal/evaluators/ChatGPT/Vanilla/result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Normal/evaluators/ChatGPT-0301/Metrics_Reference/statistics.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Normal/evaluators/ChatGPT-0301/Metrics_Reference/result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Normal/evaluators/ChatGPT-0301/Swap/statistics.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Normal/evaluators/ChatGPT-0301/Swap/result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Normal/evaluators/ChatGPT-0301/Swap_CoT/statistics.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Normal/evaluators/ChatGPT-0301/Swap_CoT/result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Normal/evaluators/ChatGPT-0301/CoT/statistics.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Normal/evaluators/ChatGPT-0301/CoT/result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Normal/evaluators/ChatGPT-0301/Vanilla/statistics.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Normal/evaluators/ChatGPT-0301/Vanilla/result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Normal/evaluators/GPT-4/Metrics_Reference/statistics.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Normal/evaluators/GPT-4/Metrics_Reference/result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Normal/evaluators/GPT-4/Swap/statistics.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Normal/evaluators/GPT-4/Swap/result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Normal/evaluators/GPT-4/Swap_CoT/statistics.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Normal/evaluators/GPT-4/Swap_CoT/result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Normal/evaluators/GPT-4/CoT/statistics.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Normal/evaluators/GPT-4/CoT/result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Normal/evaluators/GPT-4/Vanilla/statistics.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Normal/evaluators/GPT-4/Vanilla/result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Normal/evaluators/Falcon/Metrics_Reference/statistics.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Normal/evaluators/Falcon/Metrics_Reference/result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Normal/evaluators/Falcon/Swap/statistics.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Normal/evaluators/Falcon/Swap/result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Normal/evaluators/Falcon/Swap_CoT/statistics.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Normal/evaluators/Falcon/Swap_CoT/result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Normal/evaluators/Falcon/CoT/statistics.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Normal/evaluators/Falcon/CoT/result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Normal/evaluators/Falcon/Vanilla/statistics.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Normal/evaluators/Falcon/Vanilla/result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Normal/evaluators/PaLM2/Metrics_Reference/statistics.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Normal/evaluators/PaLM2/Metrics_Reference/result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Normal/evaluators/PaLM2/Swap/statistics.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Normal/evaluators/PaLM2/Swap/result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Normal/evaluators/PaLM2/Swap_CoT/statistics.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Normal/evaluators/PaLM2/Swap_CoT/result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Normal/evaluators/PaLM2/CoT/statistics.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Normal/evaluators/PaLM2/CoT/result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Normal/evaluators/PaLM2/Vanilla/statistics.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Normal/evaluators/PaLM2/Vanilla/result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Normal/dataset.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Constraint/evaluators/LLaMA2/Metrics_Reference/statistics.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Constraint/evaluators/LLaMA2/Metrics_Reference/result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Constraint/evaluators/LLaMA2/Swap/statistics.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Constraint/evaluators/LLaMA2/Swap/result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Constraint/evaluators/LLaMA2/Swap_CoT/statistics.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Constraint/evaluators/LLaMA2/Swap_CoT/result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Constraint/evaluators/LLaMA2/CoT/statistics.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Constraint/evaluators/LLaMA2/CoT/result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Constraint/evaluators/LLaMA2/Vanilla/statistics.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Constraint/evaluators/LLaMA2/Vanilla/result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Constraint/evaluators/ChatGPT/Metrics_Reference/statistics.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Constraint/evaluators/ChatGPT/Metrics_Reference/result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Constraint/evaluators/ChatGPT/Swap/statistics.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Constraint/evaluators/ChatGPT/Swap/result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Constraint/evaluators/ChatGPT/Swap_CoT/statistics.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Constraint/evaluators/ChatGPT/Swap_CoT/result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Constraint/evaluators/ChatGPT/CoT/statistics.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Constraint/evaluators/ChatGPT/CoT/result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Constraint/evaluators/ChatGPT/Vanilla/statistics.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Constraint/evaluators/ChatGPT/Vanilla/result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Constraint/evaluators/ChatGPT-0301/Metrics_Reference/statistics.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Constraint/evaluators/ChatGPT-0301/Metrics_Reference/result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Constraint/evaluators/ChatGPT-0301/Swap/statistics.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Constraint/evaluators/ChatGPT-0301/Swap/result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Constraint/evaluators/ChatGPT-0301/Swap_CoT/statistics.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Constraint/evaluators/ChatGPT-0301/Swap_CoT/result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Constraint/evaluators/ChatGPT-0301/CoT/statistics.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Constraint/evaluators/ChatGPT-0301/CoT/result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Constraint/evaluators/ChatGPT-0301/Vanilla/statistics.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Constraint/evaluators/ChatGPT-0301/Vanilla/result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/CaseStudy/Constraint/evaluators/GPT-4/Metrics_Reference/statistics.json

In [14]:
import os

dataset_dir = "/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset"

for item in sorted(os.listdir(dataset_dir)):
    print(item)

CaseStudy
LLMBar
Processed

In [15]:
import os

llmbar_path = "/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar"

print("Folders:")
for item in sorted(os.listdir(llmbar_path)):
    print(item)

Folders:
Adversarial
Natural

In [16]:
import os

llmbar_path = "/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar"

for subset in ["Natural", "Adversarial"]:
    print(f"\n===== {subset} =====")
    subset_path = os.path.join(llmbar_path, subset)

    for root, dirs, files in os.walk(subset_path):
        print(root)
        for f in files:
            print("   ", f)

===== Natural =====
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural
    dataset.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/LLaMA2
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/LLaMA2/Vanilla_1shot
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/LLaMA2/Metrics_Reference
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/LLaMA2/Swap
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/LLaMA2/Vanilla_NoRules
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/LLaMA2/Vanilla_2shot
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/LLaMA2/Reference
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/LLaMA2/Swap_CoT
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/LLaMA2/Metrics
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/LLaMA2/CoT
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/LLaMA2/Vanilla
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/ChatGPT
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/ChatGPT/Vanilla_1shot
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/ChatGPT/Metrics_Reference
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/ChatGPT/Rating_NoRules
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/ChatGPT/Swap
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/ChatGPT/Vanilla_NoRules
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/ChatGPT/Rating
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/ChatGPT/Vanilla_2shot
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/ChatGPT/Reference
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/ChatGPT/Swap_CoT
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/ChatGPT/Metrics
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/ChatGPT/CoT
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/ChatGPT/Vanilla
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/ChatGPT-0301
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/ChatGPT-0301/Vanilla_1shot
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/ChatGPT-0301/Metrics_Reference
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/ChatGPT-0301/Swap
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/ChatGPT-0301/Vanilla_NoRules
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/ChatGPT-0301/Vanilla_2shot
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/ChatGPT-0301/Reference
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/ChatGPT-0301/Swap_CoT
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/ChatGPT-0301/Metrics
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/ChatGPT-0301/CoT
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/ChatGPT-0301/Vanilla
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/GPT-4
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/GPT-4/Rating_Metrics
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/GPT-4/Vanilla_1shot
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/GPT-4/Metrics_Reference
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/GPT-4/Rating_Metrics_Reference
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/GPT-4/Rating_NoRules
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/GPT-4/Swap
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/GPT-4/Vanilla_NoRules
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/GPT-4/Rating_Reference
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/GPT-4/Rating
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/GPT-4/Vanilla_2shot
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/GPT-4/Reference
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/GPT-4/Swap_CoT
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/GPT-4/Metrics
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/GPT-4/CoT
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/GPT-4/Vanilla
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/Falcon
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/Falcon/Vanilla_1shot
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/Falcon/Metrics_Reference
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/Falcon/Swap
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/Falcon/Vanilla_NoRules
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/Falcon/Vanilla_2shot
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/Falcon/Reference
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/Falcon/Swap_CoT
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/Falcon/Metrics
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/Falcon/CoT
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/Falcon/Vanilla
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/PaLM2
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/PaLM2/Metrics_Reference
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/PaLM2/Swap
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/PaLM2/Vanilla_NoRules
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/PaLM2/Reference
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/PaLM2/Swap_CoT
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/PaLM2/Metrics
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/PaLM2/CoT
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/PaLM2/Vanilla
    statistics.json
    result.json

===== Adversarial =====
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual
    dataset.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/LLaMA2
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/LLaMA2/Vanilla_1shot
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/LLaMA2/Metrics_Reference
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/LLaMA2/Swap
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/LLaMA2/Vanilla_NoRules
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/LLaMA2/Vanilla_2shot
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/LLaMA2/Reference
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/LLaMA2/Swap_CoT
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/LLaMA2/Metrics
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/LLaMA2/CoT
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/LLaMA2/Vanilla
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/ChatGPT
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/ChatGPT/Vanilla_1shot
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/ChatGPT/Metrics_Reference
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/ChatGPT/Rating_NoRules
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/ChatGPT/Swap
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/ChatGPT/Vanilla_NoRules
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/ChatGPT/Rating
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/ChatGPT/Vanilla_2shot
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/ChatGPT/Reference
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/ChatGPT/Swap_CoT
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/ChatGPT/Metrics
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/ChatGPT/CoT
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/ChatGPT/Vanilla
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/ChatGPT-0301
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/ChatGPT-0301/Vanilla_1shot
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/ChatGPT-0301/Metrics_Reference
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/ChatGPT-0301/Swap
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/ChatGPT-0301/Vanilla_NoRules
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/ChatGPT-0301/Vanilla_2shot
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/ChatGPT-0301/Reference
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/ChatGPT-0301/Swap_CoT
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/ChatGPT-0301/Metrics
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/ChatGPT-0301/CoT
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/ChatGPT-0301/Vanilla
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/GPT-4
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/GPT-4/Rating_Metrics
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/GPT-4/Vanilla_1shot
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/GPT-4/Metrics_Reference
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/GPT-4/Rating_Metrics_Reference
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/GPT-4/Rating_NoRules
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/GPT-4/Swap
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/GPT-4/Vanilla_NoRules
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/GPT-4/Rating_Reference
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/GPT-4/Rating
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/GPT-4/Vanilla_2shot
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/GPT-4/Reference
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/GPT-4/Swap_CoT
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/GPT-4/Metrics
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/GPT-4/CoT
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/GPT-4/Vanilla
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/Falcon
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/Falcon/Vanilla_1shot
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/Falcon/Metrics_Reference
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/Falcon/Swap
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/Falcon/Vanilla_NoRules
    statistics.json
    result.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/Falcon/Vanilla_2shot
    statistics.json
    result.json

In [19]:
import os

llmbar_root = "/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar"

for root, dirs, files in os.walk(llmbar_root):
    print(f"\n📁 {root}")
    for file in files:
        print("   ", file)

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural
    dataset.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/LLaMA2

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/LLaMA2/Vanilla_1shot
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/LLaMA2/Metrics_Reference
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/LLaMA2/Swap
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/LLaMA2/Vanilla_NoRules
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/LLaMA2/Vanilla_2shot
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/LLaMA2/Reference
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/LLaMA2/Swap_CoT
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/LLaMA2/Metrics
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/LLaMA2/CoT
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/LLaMA2/Vanilla
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/ChatGPT

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/ChatGPT/Vanilla_1shot
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/ChatGPT/Metrics_Reference
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/ChatGPT/Rating_NoRules
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/ChatGPT/Swap
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/ChatGPT/Vanilla_NoRules
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/ChatGPT/Rating
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/ChatGPT/Vanilla_2shot
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/ChatGPT/Reference
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/ChatGPT/Swap_CoT
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/ChatGPT/Metrics
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/ChatGPT/CoT
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/ChatGPT/Vanilla
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/ChatGPT-0301

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/ChatGPT-0301/Vanilla_1shot
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/ChatGPT-0301/Metrics_Reference
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/ChatGPT-0301/Swap
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/ChatGPT-0301/Vanilla_NoRules
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/ChatGPT-0301/Vanilla_2shot
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/ChatGPT-0301/Reference
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/ChatGPT-0301/Swap_CoT
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/ChatGPT-0301/Metrics
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/ChatGPT-0301/CoT
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/ChatGPT-0301/Vanilla
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/GPT-4

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/GPT-4/Rating_Metrics
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/GPT-4/Vanilla_1shot
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/GPT-4/Metrics_Reference
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/GPT-4/Rating_Metrics_Reference
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/GPT-4/Rating_NoRules
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/GPT-4/Swap
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/GPT-4/Vanilla_NoRules
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/GPT-4/Rating_Reference
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/GPT-4/Rating
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/GPT-4/Vanilla_2shot
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/GPT-4/Reference
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/GPT-4/Swap_CoT
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/GPT-4/Metrics
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/GPT-4/CoT
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/GPT-4/Vanilla
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/Falcon

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/Falcon/Vanilla_1shot
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/Falcon/Metrics_Reference
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/Falcon/Swap
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/Falcon/Vanilla_NoRules
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/Falcon/Vanilla_2shot
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/Falcon/Reference
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/Falcon/Swap_CoT
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/Falcon/Metrics
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/Falcon/CoT
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/Falcon/Vanilla
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/PaLM2

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/PaLM2/Metrics_Reference
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/PaLM2/Swap
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/PaLM2/Vanilla_NoRules
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/PaLM2/Reference
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/PaLM2/Swap_CoT
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/PaLM2/Metrics
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/PaLM2/CoT
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/PaLM2/Vanilla
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual
    dataset.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/LLaMA2

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/LLaMA2/Vanilla_1shot
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/LLaMA2/Metrics_Reference
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/LLaMA2/Swap
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/LLaMA2/Vanilla_NoRules
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/LLaMA2/Vanilla_2shot
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/LLaMA2/Reference
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/LLaMA2/Swap_CoT
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/LLaMA2/Metrics
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/LLaMA2/CoT
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/LLaMA2/Vanilla
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/ChatGPT

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/ChatGPT/Vanilla_1shot
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/ChatGPT/Metrics_Reference
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/ChatGPT/Rating_NoRules
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/ChatGPT/Swap
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/ChatGPT/Vanilla_NoRules
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/ChatGPT/Rating
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/ChatGPT/Vanilla_2shot
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/ChatGPT/Reference
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/ChatGPT/Swap_CoT
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/ChatGPT/Metrics
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/ChatGPT/CoT
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/ChatGPT/Vanilla
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/ChatGPT-0301

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/ChatGPT-0301/Vanilla_1shot
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/ChatGPT-0301/Metrics_Reference
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/ChatGPT-0301/Swap
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/ChatGPT-0301/Vanilla_NoRules
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/ChatGPT-0301/Vanilla_2shot
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/ChatGPT-0301/Reference
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/ChatGPT-0301/Swap_CoT
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/ChatGPT-0301/Metrics
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/ChatGPT-0301/CoT
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/ChatGPT-0301/Vanilla
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/GPT-4

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/GPT-4/Rating_Metrics
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/GPT-4/Vanilla_1shot
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/GPT-4/Metrics_Reference
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/GPT-4/Rating_Metrics_Reference
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/GPT-4/Rating_NoRules
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/GPT-4/Swap
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/GPT-4/Vanilla_NoRules
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/GPT-4/Rating_Reference
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/GPT-4/Rating
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/GPT-4/Vanilla_2shot
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/GPT-4/Reference
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/GPT-4/Swap_CoT
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/GPT-4/Metrics
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/GPT-4/CoT
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/GPT-4/Vanilla
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/Falcon

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/Falcon/Vanilla_1shot
    statistics.json
    result.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators/Falcon/Metrics_Reference
    statistics.json
    result.json


In [20]:
import os

alpaca_root = "/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval"

for root, dirs, files in os.walk(alpaca_root):
    print(f"\n📁 {root}")
    for file in files:
        print("   ", file)

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval
    requirements.txt
    setup.py
    CITATION.cff
    LICENSE
    .pre-commit-config.yaml
    README.md
    MANIFEST.in
    .gitignore
    pytest.ini

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/.github

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/.github/workflows
    integration_tests.yml
    test_update_leaderboard.yml
    set_version.py
    unit_tests.yml
    update_pypi.yml
    update_leaderboard.yml

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/docs
    format_export_leaderboards.py
    AlpacaFarm_small.png
    check_unwanted_files.py
    format_sample_sheets.py
    index.html

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/docs/data_AlpacaEval
    claude_leaderboard.csv
    chatgpt_fn_leaderboard.csv
    alpaca_eval_gpt4_leaderboard.csv

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/docs/data_AlpacaEval_2
    alpaca_eval_gpt4_turbo_fn_leaderboard.csv
    claude_3_opus_ranking_leaderboard.csv
    alpaca_eval_cot_gpt4_turbo_fn_leaderboard.csv
    weighted_alpaca_eval_gpt4_turbo_leaderboard.csv
    mistral-large-2402_ranking_leaderboard.csv

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/tests
    test_main.py
    test_pairwise_evaluator.py
    test_analyze.py
    __init__.py
    test_decoders_unit.py

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/tests/integration_tests
    test_decoders_integration.py
    test_example_integration.py

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/Samba-CoE-v0.2-best-of-16
    model_outputs.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/Samba-CoE-v0.2-best-of-16/weighted_alpaca_eval_gpt4_turbo
    annotations.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/claude
    model_outputs.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/claude/weighted_alpaca_eval_gpt4_turbo
    annotations.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/claude/alpaca_eval_gpt4
    annotations.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/gemma-2b-it
    model_outputs.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/gemma-2b-it/weighted_alpaca_eval_gpt4_turbo
    annotations.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/merlinite-7B-AOT
    model_outputs.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/merlinite-7B-AOT/weighted_alpaca_eval_gpt4_turbo
    annotations.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/bedrock_claude
    model_outputs.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/bedrock_claude/bedrock_claude
    annotations.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/pairrm-tulu-2-13b
    model_outputs.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/pairrm-tulu-2-13b/weighted_alpaca_eval_gpt4_turbo
    annotations.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/pairrm-tulu-2-13b/alpaca_eval_gpt4
    annotations.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/causallm-14b
    model_outputs.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/causallm-14b/weighted_alpaca_eval_gpt4_turbo
    annotations.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/causallm-14b/alpaca_eval_gpt4
    annotations.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/Starling-LM-7B-beta-ExPO
    model_outputs.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/Starling-LM-7B-beta-ExPO/weighted_alpaca_eval_gpt4_turbo
    annotations.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/Storm-7B
    model_outputs.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/Storm-7B/weighted_alpaca_eval_gpt4_turbo
    annotations.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/openbuddy-falcon-40b-v9
    model_outputs.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/openbuddy-falcon-40b-v9/weighted_alpaca_eval_gpt4_turbo
    annotations.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/gemma-2-9b-it-SimPO
    model_outputs.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/gemma-2-9b-it-SimPO/weighted_alpaca_eval_gpt4_turbo
    annotations.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/aligner-2b_qwen1.5-72b-chat
    model_outputs.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/aligner-2b_qwen1.5-72b-chat/weighted_alpaca_eval_gpt4_turbo
    annotations.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/gpt4_1106_preview_verbose
    model_outputs.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/gpt4_1106_preview_verbose/weighted_alpaca_eval_gpt4_turbo
    annotations.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/Starling-LM-7B-alpha
    model_outputs.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/Starling-LM-7B-alpha/weighted_alpaca_eval_gpt4_turbo
    annotations.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/ultralm-13b-v2.0-best-of-16
    model_outputs.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/ultralm-13b-v2.0-best-of-16/weighted_alpaca_eval_gpt4_turbo
    annotations.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/ultralm-13b-v2.0-best-of-16/alpaca_eval_gpt4
    annotations.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/gpt4
    model_outputs.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/gpt4/weighted_alpaca_eval_gpt4_turbo
    annotations.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/gpt4/alpaca_eval_cot_gpt4_turbo_fn
    annotations.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/gpt4/alpaca_eval_gpt4
    annotations.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/text_davinci_003
    model_outputs.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/text_davinci_003/weighted_alpaca_eval_gpt4_turbo
    annotations.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/Storm-7B-best-of-64
    model_outputs.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/Storm-7B-best-of-64/weighted_alpaca_eval_gpt4_turbo
    annotations.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/wizardlm-13b-v1.1
    model_outputs.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/wizardlm-13b-v1.1/weighted_alpaca_eval_gpt4_turbo
    annotations.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/Infinity-Instruct-3M-0613-Mistral-7B
    model_outputs.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/Infinity-Instruct-3M-0613-Mistral-7B/weighted_alpaca_eval_gpt4_turbo
    annotations.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/tulu-2-dpo-70b-ExPO
    model_outputs.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/tulu-2-dpo-70b-ExPO/weighted_alpaca_eval_gpt4_turbo
    annotations.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/internlm2-chat-20b-ppo
    model_outputs.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/internlm2-chat-20b-ppo/weighted_alpaca_eval_gpt4_turbo
    annotations.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/REBEL-Llama-3-8B-Instruct-Armo
    model_outputs.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/REBEL-Llama-3-8B-Instruct-Armo/weighted_alpaca_eval_gpt4_turbo
    annotations.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/claude-2.1_verbose
    model_outputs.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/claude-2.1_verbose/weighted_alpaca_eval_gpt4_turbo
    annotations.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/minichat-1.5-3b
    model_outputs.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/minichat-1.5-3b/weighted_alpaca_eval_gpt4_turbo
    annotations.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/minichat-1.5-3b/alpaca_eval_gpt4
    annotations.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/tulu-2-dpo-13b-ExPO
    model_outputs.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/tulu-2-dpo-13b-ExPO/weighted_alpaca_eval_gpt4_turbo
    annotations.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/Qwen1.5-7B-Chat
    model_outputs.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/Qwen1.5-7B-Chat/weighted_alpaca_eval_gpt4_turbo
    annotations.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/Mixtral-8x7B-Instruct-v0.1_verbose
    model_outputs.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/Mixtral-8x7B-Instruct-v0.1_verbose/weighted_alpaca_eval_gpt4_turbo
    annotations.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/vicuna-13b-v1.3
    model_outputs.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/vicuna-13b-v1.3/weighted_alpaca_eval_gpt4_turbo
    annotations.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/gpt-3.5-turbo-0301
    model_outputs.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/gpt-3.5-turbo-0301/weighted_alpaca_eval_gpt4_turbo
    annotations.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/gpt-3.5-turbo-0301/alpaca_eval_cot_gpt4_turbo_fn
    annotations.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/gpt-3.5-turbo-0301/alpaca_eval_gpt4_turbo_fn
    annotations.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/gpt-3.5-turbo-0301/alpaca_eval_gpt4
    annotations.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/LMCocktail-10.7B-v1
    model_outputs.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/LMCocktail-10.7B-v1/weighted_alpaca_eval_gpt4_turbo
    annotations.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/LMCocktail-10.7B-v1/alpaca_eval_gpt4
    annotations.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/Infinity-Instruct-3M-0625-Mistral-7B
    model_outputs.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/Infinity-Instruct-3M-0625-Mistral-7B/weighted_alpaca_eval_gpt4_turbo
    annotations.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/SPPO-Llama-3-8B-Instruct-GPM-2B
    model_outputs.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/SPPO-Llama-3-8B-Instruct-GPM-2B/weighted_alpaca_eval_gpt4_turbo
    annotations.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/vicuna-33b-v1.3
    model_outputs.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/vicuna-33b-v1.3/weighted_alpaca_eval_gpt4_turbo
    annotations.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/vicuna-33b-v1.3/alpaca_eval_cot_gpt4_turbo_fn
    annotations.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/llama-2-7b-chat-hf
    model_outputs.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/llama-2-7b-chat-hf/weighted_alpaca_eval_gpt4_turbo
    annotations.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/llama-2-7b-chat-hf/alpaca_eval_gpt4
    annotations.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/alpaca-7b_concise
    model_outputs.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/alpaca-7b_concise/weighted_alpaca_eval_gpt4_turbo
    annotations.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/Infinity-Instruct-3M-0613-Llama3-70B
    model_outputs.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/Infinity-Instruct-3M-0613-Llama3-70B/weighted_alpaca_eval_gpt4_turbo
    annotations.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/Mixtral-8x7B-Instruct-v0.1_concise
    model_outputs.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/Mixtral-8x7B-Instruct-v0.1_concise/weighted_alpaca_eval_gpt4_turbo
    annotations.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/baize-v2-7b
    model_outputs.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/baize-v2-7b/weighted_alpaca_eval_gpt4_turbo
    annotations.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/Starling-LM-7B-alpha-ExPO
    model_outputs.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/Starling-LM-7B-alpha-ExPO/weighted_alpaca_eval_gpt4_turbo
    annotations.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/llama-2-70b-chat-hf
    model_outputs.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/llama-2-70b-chat-hf/weighted_alpaca_eval_gpt4_turbo
    annotations.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/llama-2-70b-chat-hf/alpaca_eval_cot_gpt4_turbo_fn
    annotations.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/llama-2-70b-chat-hf/alpaca_eval_gpt4
    annotations.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/Infinity-Instruct-3M-0625-Yi-1.5-9B
    model_outputs.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/Infinity-Instruct-3M-0625-Yi-1.5-9B/weighted_alpaca_eval_gpt4_turbo
    annotations.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/openchat-v3.1-13b
    model_outputs.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/openchat-v3.1-13b/weighted_alpaca_eval_gpt4_turbo
    annotations.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/humpback-llama-65b
    model_outputs.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/humpback-llama-65b/weighted_alpaca_eval_gpt4_turbo
    annotations.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/Infinity-Instruct-7M-Gen-Llama3_1-70B
    model_outputs.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/Infinity-Instruct-7M-Gen-Llama3_1-70B/weighted_alpaca_eval_gpt4_turbo
    annotations.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/Meta-Llama-3.1-8B-Instruct-Turbo
    model_outputs.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/Meta-Llama-3.1-8B-Instruct-Turbo/weighted_alpaca_eval_gpt4_turbo
    annotations.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/ghost-7b-alpha
    model_outputs.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/ghost-7b-alpha/alpaca_eval_gpt4
    annotations.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/text_davinci_001
    model_outputs.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/text_davinci_001/weighted_alpaca_eval_gpt4_turbo
    annotations.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/text_davinci_001/alpaca_eval_gpt4
    annotations.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/openchat-13b
    model_outputs.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/openchat-13b/weighted_alpaca_eval_gpt4_turbo
    annotations.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/gpt4_0613
    model_outputs.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/gpt4_0613/weighted_alpaca_eval_gpt4_turbo
    annotations.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/Nanbeige2-8B-Chat
    model_outputs.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/Nanbeige2-8B-Chat/weighted_alpaca_eval_gpt4_turbo
    annotations.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/platolm-7b
    model_outputs.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/platolm-7b/weighted_alpaca_eval_gpt4_turbo
    annotations.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/platolm-7b/alpaca_eval_gpt4
    annotations.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/vicuna-13b
    model_outputs.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/vicuna-13b/weighted_alpaca_eval_gpt4_turbo
    annotations.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/vicuna-13b/alpaca_eval_gpt4
    annotations.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/alpaca-farm-ppo-sim-gpt4-20k
    model_outputs.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/alpaca-farm-ppo-sim-gpt4-20k/weighted_alpaca_eval_gpt4_turbo
    annotations.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/gpt-3.5-turbo-1106_verbose
    model_outputs.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/gpt-3.5-turbo-1106_verbose/weighted_alpaca_eval_gpt4_turbo
    annotations.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/Llama-3-Instruct-8B-WPO-HB-v2
    model_outputs.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/Llama-3-Instruct-8B-WPO-HB-v2/weighted_alpaca_eval_gpt4_turbo
    annotations.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/yi-large-preview
    model_outputs.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/yi-large-preview/weighted_alpaca_eval_gpt4_turbo
    annotations.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/Snorkel-Mistral-PairRM-DPO
    model_outputs.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/Snorkel-Mistral-PairRM-DPO/weighted_alpaca_eval_gpt4_turbo
    annotations.json

📁 /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/alpacaeval/results/Mistral-7B-Instruct-v0.2
    model_outputs.json


In [21]:
import pandas as pd
from pathlib import Path

PROCESSED_DATA = PROJECT_ROOT / "datasets" / "processed"
PROCESSED_DATA.mkdir(parents=True, exist_ok=True)

UNIFIED_COLUMNS = [
    "dataset",
    "subset",
    "sample_id",
    "instruction",
    "response_a",
    "response_b",
    "gold_label",
    "turn",
    "model_a",
    "model_b"
]

unified_df = pd.DataFrame(columns=UNIFIED_COLUMNS)

print(unified_df)

Empty DataFrame
Columns: [dataset, subset, sample_id, instruction, response_a, response_b, gold_label, turn, model_a, model_b]
Index: []

In [22]:
def convert_mtbench(mt_df):
    rows = []

    for _, row in mt_df.iterrows():

        conv_a = row["conversation_a"]
        conv_b = row["conversation_b"]

        # Extract user instruction
        instruction = ""
        for msg in conv_a:
            if msg.get("role") == "user":
                instruction = msg.get("content", "")
                break

        # Extract Assistant A response
        response_a = ""
        for msg in reversed(conv_a):
            if msg.get("role") == "assistant":
                response_a = msg.get("content", "")
                break

        # Extract Assistant B response
        response_b = ""
        for msg in reversed(conv_b):
            if msg.get("role") == "assistant":
                response_b = msg.get("content", "")
                break

        rows.append({
             "dataset": "MTBench",
    "subset": "GPT4_Pair",
    "sample_id": row["question_id"],
    "instruction": instruction,
    "response_a": response_a,
    "response_b": response_b,
    "gold_label": row["winner"],
    "turn": row["turn"],
    "model_a": row["model_a"],
    "model_b": row["model_b"]
            }
        )

    return pd.DataFrame(rows)

In [23]:
mtbench_unified = convert_mtbench(mt_df)

print(mtbench_unified.shape)
mtbench_unified.head()

(2400, 10)

,dataset,subset,sample_id,instruction,response_a,response_b,gold_label,turn,model_a,model_b
0,MTBench,GPT4_Pair,81,Compose an engaging travel blog post about a r...,Aloha! I recently had the pleasure of visiting...,Here is the travel blog post rewritten with ev...,model_b,1,alpaca-13b,claude-v1
1,MTBench,GPT4_Pair,81,Compose an engaging travel blog post about a r...,Aloha! I recently had the pleasure of visiting...,Here is the travel blog post rewritten with ev...,model_b,2,alpaca-13b,claude-v1
2,MTBench,GPT4_Pair,81,Compose an engaging travel blog post about a r...,Aloha! I recently had the pleasure of visiting...,Absolutely! A recent trip to the beautiful isl...,model_b,1,alpaca-13b,gpt-3.5-turbo
3,MTBench,GPT4_Pair,81,Compose an engaging travel blog post about a r...,Aloha! I recently had the pleasure of visiting...,Absolutely! A recent trip to the beautiful isl...,model_b,2,alpaca-13b,gpt-3.5-turbo
4,MTBench,GPT4_Pair,81,Compose an engaging travel blog post about a r...,Aloha! I recently had the pleasure of visiting...,"Astonishing adventures awaited me in Hawaii, t...",model_b,1,alpaca-13b,gpt-4

In [24]:
!find /content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar -maxdepth 3

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/LLaMA2
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/ChatGPT
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/ChatGPT-0301
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/GPT-4
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/Falcon
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/evaluators/PaLM2
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/dataset.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/evaluators
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Manual/dataset.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/GPTInst
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/GPTInst/evaluators
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/GPTInst/dataset.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Neighbor
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Neighbor/evaluators
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/Neighbor/dataset.json
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/GPTOut
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/GPTOut/evaluators
/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Adversarial/GPTOut/dataset.json

In [25]:
import json

path = "/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw/LLMBar/Dataset/LLMBar/Natural/dataset.json"

with open(path, "r") as f:
    data = json.load(f)

print(type(data))
print("Number of samples:", len(data))
print("\nKeys:")
print(data[0].keys())

print("\nFirst sample:")
print(data[0])

<class 'list'>
Number of samples: 100

Keys:
dict_keys(['input', 'output_1', 'output_2', 'label'])

First sample:
{'input': "Summarize the following content.\n\nMy girlfriend is Malaysian and has been studying in the UK for the past 3 years. We have been in a relationship for 2 ½ years now.\nHer visa to stay here is coming to an end later this year, then she will be forced to return to Malaysia despite opting to stay here if she had the choice. We have gone down the job route, to the point that she was offered the job here, but the employer failed to get a license to issue Visas on very petty grounds.\nI (and others) have suggested getting married. It is something we've discussed before, and we are both happy to do it except that she refuses to get married before she goes back as she feels like she will just be doing it so she can get a visa, rather than because she will actually be married. She's happy for me to propose in 6 months, but not before she returns. The problem for me is that the delay will mean we are not going to be close to one another for at least a year, perhaps longer, other than for short visits (we both will be working full time).\nRight now, I am positive and optimistic about our situation as I think that we can make it work, but two people living in entirely different cultures on opposite sides of the world might mean that we change a lot.\nCan anyone offer any advice on how to make this work, or just a new perspective on the situation?", 'output_1': "My girlfriend's visa to stay in the UK expires in a few months, and she wants to stay here, but she won't get married until she goes back to Malaysia.", 'output_2': 'My girlfriend is Malaysian and has been studying in the UK for the past 3 years. We have been in a relationship for 2 ½ years now.', 'label': 1}

In [26]:
import json
import pandas as pd
from pathlib import Path

LLMBAR_ROOT = PROJECT_ROOT / "datasets" / "raw" / "LLMBar" / "Dataset" / "LLMBar"

def convert_llmbar():

    rows = []

    dataset_files = {
        "Natural": LLMBAR_ROOT / "Natural" / "dataset.json",
        "GPTInst": LLMBAR_ROOT / "Adversarial" / "GPTInst" / "dataset.json",
        "GPTOut": LLMBAR_ROOT / "Adversarial" / "GPTOut" / "dataset.json",
        "Manual": LLMBAR_ROOT / "Adversarial" / "Manual" / "dataset.json",
        "Neighbor": LLMBAR_ROOT / "Adversarial" / "Neighbor" / "dataset.json",
    }

    sample_id = 0

    for subset, filepath in dataset_files.items():

        with open(filepath, "r") as f:
            data = json.load(f)

        print(f"{subset}: {len(data)} samples")

        for sample in data:

            rows.append({

                "dataset": "LLMBar",
                "subset": subset,

                "sample_id": sample_id,

                "instruction": sample["input"],

                "response_a": sample["output_1"],

                "response_b": sample["output_2"],

                "gold_label": (
    "model_a"
    if sample["label"] == 1
    else "model_b"
),

                "turn": 1,

                "model_a": "Unknown",

                "model_b": "Unknown"

            })

            sample_id += 1

    return pd.DataFrame(rows)

In [27]:
llmbar_unified = convert_llmbar()

llmbar_unified.head()

Natural: 100 samples
GPTInst: 92 samples
GPTOut: 47 samples
Manual: 46 samples
Neighbor: 134 samples

,dataset,subset,sample_id,instruction,response_a,response_b,gold_label,turn,model_a,model_b
0,LLMBar,Natural,0,Summarize the following content.\n\nMy girlfri...,My girlfriend's visa to stay in the UK expires...,My girlfriend is Malaysian and has been studyi...,model_a,1,Unknown,Unknown
1,LLMBar,Natural,1,Complete a brief story given the following fir...,He learned his weather report. He prepared for...,He would always mistreat it every day. He eats...,model_a,1,Unknown,Unknown
2,LLMBar,Natural,2,How many integers are in the solution of the i...,The inequality |x + 5| < 10 means that the abs...,The list of integers that satisfy the inequali...,model_a,1,Unknown,Unknown
3,LLMBar,Natural,3,Why does eating something crunchy sound so lou...,The sound is transmitted through the vibration...,The noise that crunchy foods make when we eat ...,model_a,1,Unknown,Unknown
4,LLMBar,Natural,4,Summarize the following content.\n\nMy bf only...,Boyfriend only likes to talk through text. He ...,My boyfriend only likes to text me for shallow...,model_b,1,Unknown,Unknown

In [38]:
unified_df = pd.concat(
    [mtbench_unified, llmbar_unified],
    ignore_index=True
)

print("Unified Dataset Shape:", unified_df.shape)

unified_df.head()

Unified Dataset Shape: (2819, 10)

,dataset,subset,sample_id,instruction,response_a,response_b,gold_label,turn,model_a,model_b
0,MTBench,GPT4_Pair,81,Compose an engaging travel blog post about a r...,Aloha! I recently had the pleasure of visiting...,Here is the travel blog post rewritten with ev...,model_b,1,alpaca-13b,claude-v1
1,MTBench,GPT4_Pair,81,Compose an engaging travel blog post about a r...,Aloha! I recently had the pleasure of visiting...,Here is the travel blog post rewritten with ev...,model_b,2,alpaca-13b,claude-v1
2,MTBench,GPT4_Pair,81,Compose an engaging travel blog post about a r...,Aloha! I recently had the pleasure of visiting...,Absolutely! A recent trip to the beautiful isl...,model_b,1,alpaca-13b,gpt-3.5-turbo
3,MTBench,GPT4_Pair,81,Compose an engaging travel blog post about a r...,Aloha! I recently had the pleasure of visiting...,Absolutely! A recent trip to the beautiful isl...,model_b,2,alpaca-13b,gpt-3.5-turbo
4,MTBench,GPT4_Pair,81,Compose an engaging travel blog post about a r...,Aloha! I recently had the pleasure of visiting...,"Astonishing adventures awaited me in Hawaii, t...",model_b,1,alpaca-13b,gpt-4

In [39]:
unified_df.to_csv(
    PROCESSED_DATA / "unified_dataset.csv",
    index=False
)
print("✅ Unified dataset saved.")

✅ Unified dataset saved.

In [40]:
print(unified_df["dataset"].value_counts())

print()

print(unified_df["subset"].value_counts())

dataset
MTBench    2400
LLMBar      419
Name: count, dtype: int64

subset
GPT4_Pair    2400
Neighbor      134
Natural       100
GPTInst        92
GPTOut         47
Manual         46
Name: count, dtype: int64

In [43]:
!pwd

/content/Prompt-Bias-Mitigation-SLM-Judge/datasets/raw

In [44]:
%cd /content/Prompt-Bias-Mitigation-SLM-Judge

/content/Prompt-Bias-Mitigation-SLM-Judge

In [46]:
!git status

On branch main
Your branch is up to date with 'origin/main'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	datasets/

nothing added to commit but untracked files present (use "git add" to track)

In [47]:
!find datasets -maxdepth 3

datasets
datasets/processed
datasets/processed/unified_dataset.csv
datasets/raw
datasets/raw/LLMBar
datasets/raw/LLMBar/requirements.txt
datasets/raw/LLMBar/.git
datasets/raw/LLMBar/LICENSE
datasets/raw/LLMBar/LLMEvaluator
datasets/raw/LLMBar/README.md
datasets/raw/LLMBar/.gitignore
datasets/raw/LLMBar/Dataset
datasets/raw/alpacaeval
datasets/raw/alpacaeval/.github
datasets/raw/alpacaeval/docs
datasets/raw/alpacaeval/tests
datasets/raw/alpacaeval/results
datasets/raw/alpacaeval/example
datasets/raw/alpacaeval/requirements.txt
datasets/raw/alpacaeval/src
datasets/raw/alpacaeval/setup.py
datasets/raw/alpacaeval/.git
datasets/raw/alpacaeval/CITATION.cff
datasets/raw/alpacaeval/LICENSE
datasets/raw/alpacaeval/.pre-commit-config.yaml
datasets/raw/alpacaeval/README.md
datasets/raw/alpacaeval/MANIFEST.in
datasets/raw/alpacaeval/client_configs
datasets/raw/alpacaeval/.gitignore
datasets/raw/alpacaeval/scripts
datasets/raw/alpacaeval/notebooks
datasets/raw/alpacaeval/pytest.ini
datasets/raw/alpacaeval/figures
datasets/raw/mtbench
datasets/raw/mtbench/mtbench.csv
datasets/raw/llmbar